<?php

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group([
        'key' => 'group_6388994494936',
        'title' => 'ePaper Abo Produkte',
        'fields' => [
            [
                'key' => 'field_638899444e0a7',
                'label' => 'Landwirt ePaper Österreich',
                'name' => 'wps_lawi_subproduct_lawiAustria',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'post_type' => [
                    0 => 'product',
                ],
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 1,
            ],
            [
                'key' => 'field_6388a598a9da5',
                'label' => 'Landwirt ePaper Deutschland',
                'name' => 'wps_lawi_subproduct_lawiGermany',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'post_type' => [
                    0 => 'product',
                ],
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 1,
            ],
            [
                'key' => 'field_6388a5e1a9da6',
                'label' => 'Landwirt ePaper Bio Österreich',
                'name' => 'wps_lawi_subproduct_lawiBioAustria',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'post_type' => [
                    0 => 'product',
                ],
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 1,
            ],
            [
                'key' => 'field_6388a5fca9da7',
                'label' => 'Landwirt ePaper Bio Deutschland',
                'name' => 'wps_lawi_subproduct_lawiBioGermany',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'post_type' => [
                    0 => 'product',
                ],
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 1,
            ],
            [
                'key' => 'field_6388a733a9da8',
                'label' => 'Landwirt ePaper Kombi Abo Österreich',
                'name' => 'wps_lawi_subproduct_lawiCombiAustria',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'post_type' => [
                    0 => 'product',
                ],
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 1,
            ],
            [
                'key' => 'field_6388a74ba9da9',
                'label' => 'Landwirt ePaper Kombi Abo Deutschland',
                'name' => 'wps_lawi_subproduct_lawiCombiGermany',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'post_type' => [
                    0 => 'product',
                ],
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 1,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'lawi-epaper-subscriptions',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ]);

endif;