# name: Bump version
# on:
#   push:
#     branches: [ 'master' ]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Bump version and push tag
#         id: tag_version
#         uses: mathieudutour/github-tag-action@v5
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#       - name: Create a GitHub release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ steps.tag_version.outputs.new_tag }}
#           release_name: Release ${{ steps.tag_version.outputs.new_tag }}
#           body: ${{ steps.tag_version.outputs.changelog }}
#       - name: Replace Version in Plugin 1
#         uses: datamonsters/replace-action@v2
#         with:
#           files:  'README.md'
#           replacements:  "%%version%%=${{ steps.tag_version.outputs.new_version }}"
#       - name: Replace Version in Plugin 2
#         uses: datamonsters/replace-action@v2
#         with:
#           files:  'info.json'
#           replacements:  "%%version%%=${{ steps.tag_version.outputs.new_version }}"
#       - name: Replace Version in Plugin 3
#         uses: datamonsters/replace-action@v2
#         with:
#           files:  'lawi-subscription-handling/lawi-subscription-handling.php'
#           replacements:  "%%version%%=${{ steps.tag_version.outputs.new_version }}"
#      - name: Sync to Production
#        env:
#          dest: 'e93477@e93477-ssh.services.easyname.eu:/data/web/e93477/html/apps/plugins.michael-ritsch.com/wps-plugin'
#        run: |
#          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
#          chmod 600 ./deploy_key
#          zip -r wps-plugin.zip wps-plugin
#          rsync -zvr --delete \
#            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no -p 22' \
#            --include 'wps-plugin.zip' \
#            --include 'info.json' \
#            --exclude '*' \
#            ./ ${{env.dest}}