name: Bump version
on:
  push:
    branches: [ 'master' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Replace Version in Plugin 1
        uses: datamonsters/replace-action@v2
        with:
          files:  'Readme.md'
          replacements:  "%%version%%=${{ steps.tag_version.outputs.new_version }}"
      - name: Replace Version in Plugin 2
        uses: datamonsters/replace-action@v2
        with:
          files:  'info.json'
          replacements:  "%%version%%=${{ steps.tag_version.outputs.new_version }}"  
      - name: Replace Zip Version Name in Plugin 2
        uses: datamonsters/replace-action@v2
        with:
          files:  'info.json'
          replacements:  "%%version%%=${{ steps.tag_version.outputs.new_version }}" 
      - name: Replace required Version Name in Plugin 3
        uses: datamonsters/replace-action@v2
        with:
          files:  'info.json'
          replacements:  "%%version%%=${{ steps.tag_version.outputs.new_version }}"  
      - name: Replace Version in Plugin 3
        uses: datamonsters/replace-action@v2
        with:
          files:  'lawi-subscription-handling/lawi-subscription-handling.php'
          replacements:  "%%version%%=${{ steps.tag_version.outputs.new_version }}"  
      - name: Sync to Production
        env:
          dest: 'u127-7newkoexwyyn@35.214.226.253:~/www/documentation.wp-stars.com/public_html/development/lawi-subscription-handling'
        run: |
          echo "${{secrets.AUTO_DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          zip -r lawi-subscription-handling.zip lawi-subscription-handling
          rsync -zvr --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no -p 18765' \
            --include 'lawi-subscription-handling.zip' \
            --include 'info.json' \
            --exclude '*' \
            ./ ${{env.dest}}